export interface NewClientEnquiry {
  businessName: string,
  firstName: string,
  lastName: string,
  jobTitle?: string,
  isBusinessOwner?: boolean,
  phone: string,
  email: string,
  website?: string,
  industry: string,
  hasMarketingPlan?: boolean,
  description: string,
  knownBy: string,
  hasAlreadyWorkedWithMarketingAgency?: boolean,
}